### ISSUE TITLE
Vega-power-control settings won't apply, script potentionally hanging when trying to set profile

### ISSUE THREAD

**Issue by breadland** [dasunsrule32/radeon-scripts#11]
Currently running this on Linux Mint 19.1, but I had the same problem on Ubuntu 18.04, and Kubuntu 18.04. I tried it on both the default kernel and 4.20.

I believe I got the same results on Arch with the 4.20 kernel. Specifically Antergos with the Gnome DE.

I followed all the steps. Made sure to add the amdgpu.ppfeaturemask=0xffffffff to the grub config file.
Made sure the value actually changed. I then followed the install instructions for the vega-power-control.

No problems with any of the commands and the required files were successfully copied to their respective locations.

Typing 
SYSPATH=$(awk '{print}' <<< `find /sys/devices -name power_dpm_force_performance_level -type f -exec dirname {} \;`)
cat $SYSPATH/pp_od_clk_voltage

shows me the default clocks and voltages. So 1630mhz and 1200mv, etc.

Using the 
systemctl status vega-power-control.service
watch -n 5 journalctl -n -b -u vega-power-control.service

commands I see 

Feb 08 23:56:55 CM6870 systemd[1]: Started AMD Power Control.
Feb 08 23:56:55 CM6870 vega-power-control[3992]: Kernel requirements met, continuing...
Feb 08 23:56:55 CM6870 vega-power-control[3992]: Setting profile to: balanced...

then nothing else. On each reboot it generates that log and no settings actually apply.

Not sure if I did something wrong installing the scripts all those different times and on the different distros.

I'd also like to add that I have a core i7 3770 and an Asus P8H77-M PRO motherboard because that could be relevant to the issue.

**Comment by breadland** [comment]
Oh, my bad, it looks like the balanced profile is the same as in Windows. So it's normal that I get those clocks and voltages since by default the script sets those clocks and voltages.

Now I'm going to see if I can let it use the manual profile. I'm a little inexperienced when it comes to these things.

So basically I have to edit the vega-power-control file and change DEFAULTDPMPERFLVL to "manual"?

I also changed POWERCAP to 1 since I'm on the 4.20 kernel.

**Comment by breadland** [comment]
Looks like it works now! You can close this issue.

**Comment by dasunsrule32** [comment]
What card are you using?

**Comment by breadland** [comment]
Sapphire Vega 64. But it looks like it's working fine. 

I just had to set the DEFAULTDPMPERFLVL = manual 

inside vega-power-control.

I just assumed that the custom voltages would be applied by default. 

So there's nothing wrong with the script, everything is working like it should. 

All I had to change from the manual profile were the voltages, since my Vega 64 doesn't like 1000mv at 1600mhz.
