### ISSUE TITLE
"Kernel is too old, exiting..." on Linux 5.0.0

### ISSUE THREAD

**Issue by LazyLea** [dasunsrule32/radeon-scripts#15]
It seems like the script depends on x.xx version numbers (like 4.20), but the newly released kernel uses 5.0.0 as version number and therefore resolves to 50, which is lower than 420. 

~~Replacing the command for getting the kernel version with~~

    KERNELVER=$(awk -F- '{print $1}' <<< `uname -r` | awk -F. '{print $1$2$3}')

~~seems to work for versions above 4.15 (...for now).~~

Edit: Never mind, this won't work for version numbers like 4.15.8.

**Comment by LazyLea** [comment]
Okay, I think I figured out a nice solution that should be at least a little future proof.

    KERNELVER=$(awk -F. '{printf("%01d%02d\n", $1, $2)}' <<< `uname -r`)

`4.9.23` -> `409`
`4.15.4` -> `415`
`5.0.3` -> `500`
`5.3.43` -> `503`

**Comment by dasunsrule32** [comment]
This has been merged. Thanks. :)
