### ISSUE TITLE
cp: cannot stat 'systemd/vega-power-control.service': No such file or directory

### ISSUE THREAD

**Issue by blutigJK** [dasunsrule32/radeon-scripts#18]
I have been looking around for a way to undervolt and overclock my Vega 64 and found this. However, I can't seem to get it installed for some reason.

Went through and added `amdgpu.ppfeaturemask=0xffffffff` to GRUB and confirmed it's set. Following the short guide on installing, I can copy and chmod the power and fan control, but whenever I get to
`sudo cp systemd/vega-power-control.service /etc/systemd/system`
I just get the error in the title. I checked the bin folder and both files are there. Is there something I'm missing? I get the same error for the fan control too.

Running Manjaro KDE 5.0 with the ASUS Strix Vega 64 (STRIX-RXVEGA64-O8G-GAMING)

**Comment by dasunsrule32** [comment]
Does Manjaro have the `/etc/systemd/system` folder?

**Comment by blutigJK** [comment]
Yes, it does.

**Comment by dasunsrule32** [comment]
Can you do the following?

`ls -l /etc/systemd/system/vega-power-control.service`
`ls -l /etc/systemd/system/vega-fan-control.service`

**Comment by dasunsrule32** [comment]
Make sure that you are in the root of the git folder to copy these. That will resolve your issue.
